# Generated by Django 5.1.5 on 2025-08-29 16:59

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapi', '0003_alter_skill_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='skill',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_lower_skill_name'),
        ),
    ]
