# Generated by Django 5.1.5 on 2025-08-29 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapi', '0004_skill_unique_lower_skill_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='skill',
            name='unique_lower_skill_name',
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
